### ISSUE TITLE
Setting up the Python wrapper cmake error

### ISSUE THREAD

**Issue by Ayshine** [smrfeld/cmake_cpp_pybind11_tutorial#3]
I'm having the following error while I try to run make at the setting up the Python wrapper section. May I have some help on finding out what is missing?
The output is pasted below.
```
(base) asanci@asanci:~/python/build$ make
Scanning dependencies of target automobile
make[2]: *** No rule to make target 'CMakeFiles/automobile.dir/build'.  Stop.
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/automobile.dir/all' failed
make[1]: *** [CMakeFiles/automobile.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2`
```

**Comment by smrfeld** [comment]
I checked it is working for me.

1. Can you post how you ran `cmake`?
2. The `build` folder for this step should be in the root of the project (not in the projects `python` folder). I couldn't tell from your paths if that's where it is

**Comment by Ayshine** [comment]
ok, thanks! I'll try that way and get back here.

**Comment by Ayshine** [comment]
I was getting the prior error when I put the build folder in the python folder. Now, I put it the root of the project after I cloned the code from your repo. Now, I am getting the error below 
![image](https://user-images.githubusercontent.com/28358926/117648969-99983800-b197-11eb-9f33-05ec7c38d660.png)

**Comment by smrfeld** [comment]
OK, it sounds like [this](https://stackoverflow.com/a/55748415/1427316) is the problem - your CMake version is too old, you should update to a newer version.

This is on the pybind11 side - nothing we can change in our `CMakeLists.txt`. You can try to ask the pybind11 community if you must get it working for an older CMake version

**Comment by Ayshine** [comment]
Thanks for the help @smrfeld. After upgrading my CMake version from 3.10.2 to 3.20.2, this problem is solved.
